#!/bin/bash

# Exit on error
set -e

main() {
    get_directory_of_this_app
    source_environment_variables
    source_app_config_if_exists
    create_symlink_to_this_app
    parse_arguments "$@"
}

get_directory_of_this_app() {
    APP_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
}

source_environment_variables() {
    source "$APP_DIR/env"
}

source_app_config_if_exists() {
    [ -r "$APP_CONFIG_FILE" ] && source "$APP_CONFIG_FILE" || true
}

create_symlink_to_this_app() {
    ln -sf "$APP_DIR"/run "$HOME/.local/bin/$APP_NAME_LOWER"
}

parse_arguments() {
    if [[ $# -eq 0 ]]; then
        show_usage
        exit 0
    else
        case "$1" in
            -h|--help)
                show_usage
                exit 0
                ;;
            *)
                echo "Error: Invalid option '$1'"
                show_usage
                exit 1
                ;;
        esac
    fi
}

show_usage() {
    echo "Usage: $APP_NAME_LOWER [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help          Show help"
}

# Call main function with arguments
main "$@"
